<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (C) 2011, LINDA Foundation.  All rights reserved.

      https://fsf.org

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

     * Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above
  copyright notice, this list of conditions and the following disclaimer
  in the documentation and/or other materials provided with the
  distribution.
     * Neither the name of FuseSource Corp. nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  
  <!-- Remove parent POM since it's not available in Maven Central -->
  <groupId>io.github.lindaprotocol</groupId>
  <artifactId>zksnark-java-sdk</artifactId>
  <version>1.0.1</version>
  <packaging>bundle</packaging>

  <properties>
    <forge-project-id>zksnark-java-sdk</forge-project-id>
    <forge-project-id-uc>zksnark-java-sdk</forge-project-id-uc>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <hawtjni-version>1.18</hawtjni-version>
    <commons-io-version>2.11.0</commons-io-version>
    <junit-version>4.13.2</junit-version>
    <jacoco.version>0.8.8</jacoco.version>
    <gpg.keyname>LindaProtocol</gpg.keyname>
    <!-- <gpg.keyname>0xEF7F2D6C</gpg.keyname> -->
  </properties>

  <name>ZkSNARK Java SDK</name>
  <description>A Java SDK for zkSNARK operations with native bindings to libsodium and librustzcash</description>
  <url>https://github.com/lindaprotocol/zksnark-java-sdk</url>
  <inceptionYear>2022</inceptionYear>

  <organization>
    <name>LINDA Foundation</name>
    <url>https://www.linda.network/</url>
  </organization>

  <licenses>
    <license>
      <name>Apache License 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:https://github.com/lindaprotocol/zksnark-java-sdk.git</connection>
    <developerConnection>scm:git:https://github.com/lindaprotocol/zksnark-java-sdk.git</developerConnection>
    <url>https://github.com/lindaprotocol/zksnark-java-sdk</url>
    <tag>HEAD</tag>
  </scm>

  <developers>
    <developer>
      <id>geeks</id>
      <name>LINDA Foundation Development Team</name>
      <organization>LINDA</organization>
      <organizationUrl>https://www.linda.network/</organizationUrl>
    </developer>
    <developer>
      <id>halibobo</id>
      <name>halibobo1205</name>
      <organization>halibobor</organization>
      <organizationUrl>http://halibobor.com/</organizationUrl>
      <email>halibobo1205@gmail.com</email>
      <roles>
        <role>Developer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
  </developers>

  <distributionManagement>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://ossrh-staging-api.central.sonatype.com/content/repositories/snapshots/</url>
    </snapshotRepository>
    <repository>
      <id>ossrh</id>
      <url>https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>

  <dependencies>
    <dependency>
      <groupId>org.fusesource.hawtjni</groupId>
      <artifactId>hawtjni-runtime</artifactId>
      <version>${hawtjni-version}</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>${commons-io-version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit-version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.1.0</version>
      </plugin>
      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.2</version>
        <configuration>
          <redirectTestOutputToFile>true</redirectTestOutputToFile>
          <forkMode>once</forkMode>
          <argLine>@{argLine} -ea -Djava.library.path=${project.basedir}/cpp/build</argLine>
          <failIfNoTests>false</failIfNoTests>
          <workingDirectory>${project.build.directory}</workingDirectory>
          <includes>
            <include>**/*Test.java</include>
          </includes>
        </configuration>
      </plugin>
      
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <executions>
          <execution>
            <id>prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>generate-code-coverage-report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <archive>
            <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
          </archive>
        </configuration>
      </plugin>

      <!-- Source JAR -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.2.1</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <phase>package</phase>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Javadoc JAR -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.3.1</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <source>8</source>
              <encoding>${project.build.sourceEncoding}</encoding>
              <additionalOptions>
                <additionalOption>-Xdoclint:none</additionalOption>
              </additionalOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Bundle Plugin for OSGi -->
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>5.1.2</version>
        <extensions>true</extensions>
        <inherited>true</inherited>
        <configuration>
          <instructions>
            <Bundle-Name>${project.artifactId}</Bundle-Name>
            <Bundle-SymbolicName>${project.groupId}.${project.artifactId}</Bundle-SymbolicName>
            <Export-Package>
              org.linda.common.*;version=${project.version},
              org.apache.commons.*;version=${commons-io-version},
              org.fusesource.hawtjni.*;version=${hawtjni-version},
            </Export-Package>
            <Import-Package/>
            <DynamicImport-Package/>
            <Implementation-Title>zksnark JNI</Implementation-Title>
            <Implementation-Version>${project.version}</Implementation-Version>
            <Embed-Dependency>
              *;groupId=io.github.lindaprotocol.zksnark-java-sdk;inline=META-INF/native/*,
            </Embed-Dependency>
            <Embed-Transitive>true</Embed-Transitive>
            <Bundle-NativeCode>
              META-INF/native/osx64/libzksnarkjni.jnilib;osname=macosx;processor=x86-64,
              META-INF/native/osx64/aarch64/libzksnarkjni.jnilib;osname=macosx;processor=aarch64,
              META-INF/native/linux64/libzksnarkjni.so;osname=Linux;processor=x86-64,
              META-INF/native/linux64/aarch64/libzksnarkjni.so;osname=Linux;processor=aarch64
            </Bundle-NativeCode>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>release</id>
      <build>
        <plugins>
          <!-- GPG Signing -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.0.1</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
                <configuration>
                  <keyname>${gpg.keyname}</keyname>
                  <passphraseServerId>${gpg.keyname}</passphraseServerId>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <!-- Nexus Staging -->
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.8</version>
            <extensions>true</extensions>
            <configuration>
              <serverId>ossrh</serverId>
              <nexusUrl>https://ossrh-staging-api.central.sonatype.com/</nexusUrl>
              <autoReleaseAfterClose>true</autoReleaseAfterClose>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
